# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('province', 'Province'), ('city', 'City'), ('country', 'Country')], default='country', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region_cn.Region')),
            ],
        ),
    ]
